
import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marcushenriksson
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSlider = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKurs = new javax.swing.JList<>();
        comboColor = new javax.swing.JComboBox<>();
        comboColor2 = new javax.swing.JComboBox<>();
        btnMouse = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblKey = new javax.swing.JLabel();
        barProg = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSlider.setText("0");
        jPanel1.add(lblSlider);

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinimum(-50);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setPreferredSize(new java.awt.Dimension(300, 38));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel1.add(jSlider1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        listKurs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Databas", "Java OOP", "AI" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listKurs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listKursValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listKurs);

        jPanel2.add(jScrollPane1);

        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Yellow", "Blue" }));
        comboColor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboColorItemStateChanged(evt);
            }
        });
        jPanel2.add(comboColor);

        comboColor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Yellow", "Green", "Blue" }));
        comboColor2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboColor2ItemStateChanged(evt);
            }
        });
        jPanel2.add(comboColor2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        btnMouse.setText("Click Me");
        btnMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseMouseExited(evt);
            }
        });
        getContentPane().add(btnMouse, java.awt.BorderLayout.LINE_END);

        jPanel3.add(lblKey);

        barProg.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(barProg);

        jButton1.setText("Click me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jTextField1.setText("jTextField2");
        jPanel3.add(jTextField1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAreaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtArea);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        //Denna metod anropas när användaren drar i Slider-markören
        //Värdet ifrån sliders hämtas och skrivs i en label
        int value = jSlider1.getValue();
        lblSlider.setText("" + value);
    }//GEN-LAST:event_jSlider1StateChanged

    private void listKursValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listKursValueChanged
        //Denna metod anroppas när användaren väljer en kurs-namn i Listan
        //Det valda värdet hämtas ifrån listan och visas i en JOptionPane
        String strKursNamn = listKurs.getSelectedValue();
        JOptionPane.showMessageDialog(null, "Du har valt " + strKursNamn);
    }//GEN-LAST:event_listKursValueChanged

    private void comboColorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboColorItemStateChanged
        //Denna metod är ifrån en av COmboBoxarna. Den anroppas ChangeCOlor längre ner med sitt event som parameter
        ChangeColor(evt);
    }//GEN-LAST:event_comboColorItemStateChanged

    private void comboColor2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboColor2ItemStateChanged
        //Denna metod är ifrån en av COmboBoxarna. Den anroppas ChangeCOlor längre ner med sitt event som parameter
        ChangeColor(evt);
    }//GEN-LAST:event_comboColor2ItemStateChanged

    private void btnMouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseMouseEntered
        //Denna metod gär knappen Disabled när musen rör vid den
        btnMouse.setEnabled(false);
    }//GEN-LAST:event_btnMouseMouseEntered

    private void btnMouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseMouseExited
        //Denna metod gär knappen Enabled när musen lämnar den
        btnMouse.setEnabled(true);
    }//GEN-LAST:event_btnMouseMouseExited

    private void txtAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyTyped
        //Denna metod anroppas när ett tangentknapp trycks när man skriver i textfältet
        //Tangenten sparas i DataTypen Char med metoden .getKeyChar();
        char p = evt.getKeyChar();
        //Tangenten visa i en label
        lblKey.setText("" + p);
        
        //Variabel value tar strängens längd itfrån textarea
        int value = txtArea.getText().length();
        
        //Längeden säts i ProgressBar
        barProg.setValue(value);
    }//GEN-LAST:event_txtAreaKeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Hello world");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ChangeColor (ItemEvent evt) {
        //Vi skapar en referense till den ComboBox som gjorde anroppet.
        //Vi gör detta eftersom båda ComboCobxarna går hit
        javax.swing.JComboBox p = (javax.swing.JComboBox) evt.getSource();
        //Vi hämtar det valda värdet ifrån den actuella ComboBoxen
        String strColor = p.getSelectedItem().toString();
        
        //Använder ett Switch Statement för att ändra COmboBoxen till rätt färg.
        switch (strColor) {
            case "Red":
                p.setBackground(Color.RED);
                break;
            case "Blue":
                p.setBackground(Color.BLUE);
                break;
            case "Green":
                p.setBackground(Color.GREEN);
                break;
            case "Yellow":
                p.setBackground(Color.YELLOW);
                break;
            default:
                break;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barProg;
    private javax.swing.JButton btnMouse;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JComboBox<String> comboColor2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblKey;
    private javax.swing.JLabel lblSlider;
    private javax.swing.JList<String> listKurs;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
